# Generated by Django 3.1.7 on 2021-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
